stages:
  - build

before_script:
  - echo "deploy start"
after_script:
  - echo "deploy end"
  - cat index.html
deploy_production:
  stage: build
  script:
    - echo "ME=Laravel
      APP_ENV=local
      APP_KEY=ooxx
      APP_DEBUG=true
      APP_LOG_LEVEL=debug
      ">>.env
    - git rev-parse --short HEAD
    - git pull origin master
  tags:
    - tset-runner-tags
  only:
    - master
  when: always