stages:
  - deploy

before_script:
  - echo "deploy start"
after_script:
  - echo "deploy end"
  - cat index.php
deploy_production:
  stage: deploy
  script:
    - echo "ME=Laravel
      APP_ENV=local
      APP_KEY=ooxx
      APP_DEBUG=true
      APP_LOG_LEVEL=debug
      ">>.env
  tags:
    - test-runner-tags
  only:
    - master
  when: always